### ISSUE TITLE
The code works on Chrome but dont works on Firefox

### ISSUE THREAD

**Issue by lucassoarespessini** [wolffe/DragonflyJS#2]
You can see this that you open the page on   [](https://getbutterfly.com/dragonflyjs-vanilla-javascript-drag-and-drop/) on Firefox and when you open on Chrome. The console of Firefox print:

`TypeError: ev is undefined[Learn More]`

**Comment by wolffe** [comment]
It is working for me in Firefox 76.0.1 (64-bit).

What is your version of Firefox? Can I also see a screenshot of your console?

**Comment by lucassoarespessini** [comment]
It's here the page:
![image](https://user-images.githubusercontent.com/44554253/83022396-d9efbc00-a001-11ea-8de7-9bd7f4082ab1.png)
The console:
![image](https://user-images.githubusercontent.com/44554253/83022540-0e637800-a002-11ea-91b9-9ccf60c1ba30.png)
My is Mozilla Firefox 64.0

**Comment by wolffe** [comment]
Yeah, that's pretty old. It's probably the ES6 code.

You should definitely upgrade. Firefox 64 has been released on December 11, 2018.
